global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  - job_name: 'arbitrage-bot'
    static_configs:
      - targets: ['arbitrage-bot:8000']
    scrape_interval: 5s